baseURL = "http://127.0.0.1:1313"
languageCode = "zh-cn"
title = "MDTool"
theme = "theme-weixin-mp"
assetDir = "assets"

[params]
  #colorScheme="gruvbox-dark-soft"

[module]
[[module.imports]]
  path = "module-markdown-body-css"
