baseURL = "http://127.0.0.1:1313"
languageCode = "zh-cn"
title = "MDTool"
theme = ""

[module]
[[module.imports]]
  path = "style-markdown-body"

[[module.imports]]
  path = "style-chota"

[[module.imports]]
  path = "theme-base"
