baseURL = "http://127.0.0.1:1313"
languageCode = "zh-cn"
title = "Markdown Tool"
theme = ""

[module]
[[module.imports]]
  path = "base"

# [taxonomies]
#   tag = "tags"

# [menu]
# [[menu.main]]
#   name = "About"
#   url = "/about/"

[security]
[security.exec]
  allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^pandoc$']


[params]
  # 目前唯一一个 theme
  siteTheme = 'gruvbox-soft'


[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Access-Control-Allow-Origin = '*'
