baseURL = "http://127.0.0.1:1313"
languageCode = "zh-cn"
title = "Markdown Tool"
theme = ""

[module]
[[module.imports]]
  path = "style-markdown-body"

[[module.imports]]
  path = "theme-base"

# [taxonomies]
#   tag = "tags"

# [menu]
# [[menu.main]]
#   name = "About"
#   url = "/about/"
